### ISSUE TITLE
It is impossible to stop Kafka-brokers without root permission. 

### ISSUE THREAD

**Issue by nguyenngoccao** [jiksoo75/MOHA-Kafka#18]
The command to stop brokers "kill -9 7564" required with "sudo" or "root"

**Comment by IDPL-MJU** [comment]
This is probably due to the mismatch between the "creator" account and "stopping" account of Kafka-brokers. For example, Kafka-brokers launched by yarn (which is an account in our Hadoop cluster) cannot be stopped through other accounts such as jiksoo or cao. 

So, we need to investigate what is happening in the codes and if there is any error message related to the permissions.

**Comment by nguyenngoccao** [comment]
The problem probably happened because of ProcessBuilder. In the case of this command execution, ProcessBuilder doesn't seem to work properly. So, I replaced ProcessBuilder with Runtime, and the problem is solved.
